services:
  product-service:
    build:
      dockerfile: Dockerfile
      target: build
    command:
      [
        "dotnet",
        "watch",
        "--project",
        "ProductService.Presentation",
      ]
    ports:
      - "8082:8080"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: 1
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      Logging__LogLevel__Default: Trace
      Logging__LogLevel__Microsoft: Warning
      Logging__LogLevel__Microsoft.AspNetCore: Warning
      Database__Host: product-service-postgres
      Database__Database: ${Database__Database}
      Database__Username: ${Database__Username}
      Database__Password: ${Database__Password}
      Stripe__ApiKey: ${Stripe__ApiKey}
      Stripe__WebhookSecret: ${Stripe__WebhookSecret}
      Kafka__Servers: kafka:9092
    volumes:
      - ./ProductService.Presentation/src:/app/ProductService.Presentation/src
      - ./ProductService.Infrastructure/src:/app/ProductService.Infrastructure/src
      - ./ProductService.Application/src:/app/ProductService.Application/src
      - ./ProductService.Domain/src:/app/ProductService.Domain/src
  product-service-postgres-migrate:
    build:
      dockerfile: Dockerfile
      target: build
    command:
      [
        "dotnet",
        "ef",
        "database",
        "update",
        "--project",
        "ProductService.Application",
        "--",
        "--host=${Database__Host}",
        "--database=${Database__Database}",
        "--username=${Database__Username}",
        "--password=${Database__Password}"
      ]
    environment:
      Database__Host: product-service-postgres
      Database__Database: ${Database__Database}
      Database__Username: ${Database__Username}
      Database__Password: ${Database__Password}
      Kafka__Servers: kafka:9092
    volumes:
      - ./ProductService.Presentation/src:/app/ProductService.Presentation/src
      - ./ProductService.Infrastructure/src:/app/ProductService.Infrastructure/src
      - ./ProductService.Application/src:/app/ProductService.Application/src
      - ./ProductService.Application/Migrations:/app/ProductService.Application/Migrations
      - ./ProductService.Domain/src:/app/ProductService.Domain/src
  product-service-postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${Database__Username}
      POSTGRES_PASSWORD: ${Database__Password}
      POSTGRES_DB: ${Database__Database}
