services:
  order-service:
    build:
      dockerfile: Dockerfile
      target: build
    command:
      [
        "dotnet",
        "watch",
        "--project",
        "OrderService.Presentation",
      ]
    ports:
      - "8085:8080"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: 1
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      Logging__LogLevel__Default: Trace
      Logging__LogLevel__Microsoft: Warning
      Logging__LogLevel__Microsoft.AspNetCore: Warning
      Logging__LogLevel__Microsoft.AspNetCore.Authentication: Debug
      Database__Host: order-service-postgres
      Database__Database: ${Database__Database}
      Database__Username: ${Database__Username}
      Database__Password: ${Database__Password}
      Stripe__ApiKey: ${Stripe__ApiKey}
      Stripe__WebhookSecret: ${Stripe__WebhookSecret}
      Jwt__ClientId: ${Jwt__ClientId}
      Jwt__SecretClientId: ${Jwt__SecretClientId}
      Jwt__Issuer: ${Jwt__Issuer}
      Jwt__Authority: ${Jwt__Authority}
      Jwt__Audience: ${Jwt__Audience}
      MicroserviceNetworkConfig__PaymentServiceUrl: ${MicroserviceNetworkConfig__PaymentServiceUrl}
      MicroserviceNetworkConfig__ProductServiceUrl: ${MicroserviceNetworkConfig__ProductServiceUrl}
      MicroserviceNetworkConfig__UserServiceUrl: ${MicroserviceNetworkConfig__UserServiceUrl}
      Kafka__Servers: kafka:9092
    volumes:
      - ./Src:/app/Src
      - ./Properties:/app/Properties
  order-service-postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${Database__Username}
      POSTGRES_PASSWORD: ${Database__Password}
      POSTGRES_DB: ${Database__Database}

  order-service-postgres-migrate:
    build:
      dockerfile: Dockerfile
      target: build
    command:
      [
        "dotnet",
        "ef",
        "database",
        "update",
        "--project",
        "OrderService.Application",
        "--",
        "--host=${Database__Host}",
        "--database=${Database__Database}",
        "--username=${Database__Username}",
        "--password=${Database__Password}"
      ]
    restart: on-failure
    environment:
      Database__Host: store-service-postgres
      Database__Database: ${Database__Database}
      Database__Username: ${Database__Username}
      Database__Password: ${Database__Password}
    volumes:
      - ./OrderService.Presentation/Src:/app/OrderService.Presentation/Src
      - ./OrderService.Infrastructure/Src:/app/OrderService.Infrastructure/Src
      - ./OrderService.Application/Src:/app/OrderService.Application/Src
      - ./OrderService.Application/Migrations:/app/OrderService.Application/Migrations
      - ./OrderService.Domain/Src:/app/OrderService.Domain/Src
