services:
  order-service:
    build:
      dockerfile: Dockerfile
      target: build
    command:
      [
        "dotnet",
        "watch",
      ]
    ports:
      - "8085:8080"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: 1
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      Logging__LogLevel__Default: Trace
      Logging__LogLevel__Microsoft: Warning
      Logging__LogLevel__Microsoft.AspNetCore: Warning
      Database__Host: order-service-postgres
      Database__Database: ${Database__Database}
      Database__Username: ${Database__Username}
      Database__Password: ${Database__Password}
      Jwt__SigningKey: ${Jwt__SigningKey}
      Stripe__ApiKey: ${Stripe__ApiKey}
      Stripe__WebhookSecret: ${Stripe__WebhookSecret}
      MicroserviceNetworkConfig__PaymentServiceUrl: ${MicroserviceNetworkConfig__PaymentServiceUrl}
      MicroserviceNetworkConfig__ProductServiceUrl: ${MicroserviceNetworkConfig__ProductServiceUrl}
      MicroserviceNetworkConfig__UserServiceUrl: ${MicroserviceNetworkConfig__UserServiceUrl}
      Kafka__Servers: kafka:9092
    volumes:
      - ./Src:/app/Src
      - ./Properties:/app/Properties
  order-service-postgres-migrate:
    build:
      dockerfile: Dockerfile
      target: build
    command:
      [
        "dotnet",
        "ef",
        "database",
        "update",
      ]
    environment:
      Database__Host: order-service-postgres
      Database__Database: ${Database__Database}
      Database__Username: ${Database__Username}
      Database__Password: ${Database__Password}
      Kafka__Servers: kafka:9092
    volumes:
      - ./OrderService/Src:/app/OrderService/Src
  order-service-postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${Database__Username}
      POSTGRES_PASSWORD: ${Database__Password}
      POSTGRES_DB: ${Database__Database}
