apiVersion: v2
name: umbrella
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: store-service
    version: 0.1.0
    repository: file://../store-service
  - name: payment-service
    version: 0.1.0
    repository: file://../payment-service
  - name: kafka
    version: 30.1.7
    repository: oci://registry-1.docker.io/bitnamicharts
  - alias: store-service-postgres
    name: postgresql
    version: 18.1.2
    repository: https://charts.bitnami.com/bitnami
  - alias: payment-service-postgres
    name: postgresql
    version: 18.1.2
    repository: https://charts.bitnami.com/bitnami
  - name: nginx-ingress-controller
    version: 12.0.7
    repository: https://charts.bitnami.com/bitnami